import { cspellConfig } from '@kitschpatrol/cspell-config'

export default cspellConfig({
	ignorePaths: ['test/assets/test-deck-pruning/*', 'test/assets/test-unicode/*', '**/*.svg'],
	words: [
		'aesculapa',
		'clozed',
		'clozing',
		'denden',
		'encloze',
		'fassets',
		'fbase',
		'fcwd',
		'fislysandi',
		'Fpandas',
		'ftest',
		'jīng',
		'linkpath',
		'mathbf',
		'matroska',
		'mdank',
		'mdanki',
		'msvideo',
		'namespac',
		'thisnotehasaverylongonewordtitlecanwestillsplititusingthe',
		'thisnotehasaverylongonewordtitlecanwestillsplititusingthetruncationalgorithm',
		'vmatrix',
		'zhuzhige',
	],
})
