import { cspellConfig } from '@kitschpatrol/cspell-config'

export default cspellConfig({
	ignorePaths: ['test/assets/test-deck-pruning/*', 'test/assets/test-unicode/*', '**/*.svg'],
	words: [
		'aesculapa',
		'ankidown',
		'Biosa',
		'clozed',
		'clozing',
		'denden',
		'encloze',
		'fassets',
		'fbase',
		'fcwd',
		'fislysandi',
		'Flathub',
		'ftest',
		'furigana',
		'ISOGE',
		'jīng',
		'Langfield',
		'linkpath',
		'mathbf',
		'matroska',
		'mdank',
		'mdanki',
		'msvideo',
		'namespac',
		'Oleksandr',
		'quicktime',
		'Raun',
		'Shlinchak',
		'speex',
		'thisnotehasaverylongonewordtitlecanwestillsplititusingthe',
		'thisnotehasaverylongonewordtitlecanwestillsplititusingthetruncationalgorithm',
		'vmatrix',
		'Weinstein',
		'wikilink',
		'zhuzhige',
	],
})
