publicHoistPattern:
  - '@kitschpatrol/repo-config'
  - '@kitschpatrol/typescript-config'
  - 'case-police'
  - '*cspell*'
  - '*eslint*'
  - '*knip*'
  - '*mdat*'
  - '*prettier*'
  - '*remark*'
  - '*stylelint*'
allowBuilds:
  esbuild: true
  oxc-resolver: true
  puppeteer: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@kitschpatrol/*'
  - 'yanki-connect'
