import fs from 'node:fs/promises'

// Currently unused, unmodified GitHub Markdown CSS doesn't look great in Anki

const inputFilePath = './node_modules/github-markdown-css/github-markdown.css'
const outputFilePath = './src/lib/style/github-markdown-css.ts'

const cssContent = await fs.readFile(inputFilePath, 'utf8')

// Generate the module content
const moduleContent = `// Generated by generate-css.ts\n// Do not edit directly\nexport default ${JSON.stringify(cssContent)};`

// Write the module file
await fs.writeFile(outputFilePath, moduleContent)

console.log('CSS module generated successfully!')
